version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install additional tools
          command: pip install pytest==7.4.0
      - run:
          name: Run tests
          command: pytest
